language: ruby
addons:
  postgresql: '9.4'
rvm:
  - 2.2.4
gemfile: Gemfile
before_script:
  - cp config/database.yml.travis  config/database.yml
  - cp config/secrets.yml.travis  config/secrets.yml
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec
